### ISSUE TITLE
macOS 10.13.3 issue

### ISSUE THREAD

**Issue by funfunfunny** [lukas2005s-Team/Device-Mod-Apps#11]
Having a problem with the Device Mod Apps in my OS. The Mineium browser doesn't load and when I click install nothing happens. Please let me know If you have a fix or know of the prob.

**Comment by lukas2005** [comment]
Pretty sure its a bug with the Device Mod

**Comment by lukas2005** [comment]
Can you send me your mc log?

2018-04-19 1:02 GMT+02:00 funfunfunny <notifications@github.com>:

**Comment by funfunfunny** [comment]
Here u go
